### ISSUE TITLE
Error: Could not find or load main class pl.baczkowicz.mqttspy.Main

### ISSUE THREAD

**Issue by TLaren** [kamilfb/mqtt-spy#103]
Not sure if this is the right place to ask?
Running on Raspberry Pi 2 "Raspbian GNU/Linux 8 (jessie)"
Java version "1.8.0_65"
Running from the command line: java -jar mqtt-spy-0.5.4-jar-with-dependencies.jar
I get: Error: Could not find or load main class pl.baczkowicz.mqttspy.Main

Any suggestions?

Tim

**Comment by kamilfb** [comment]
Hi @TLaren. Please take a look at https://github.com/kamilfb/mqtt-spy/wiki/GettingStarted and https://github.com/kamilfb/mqtt-spy/issues/88. If still struggling after that let me know.

**Comment by TLaren** [comment]
Still no luck. Tried on a Windows box and it’s up.

Thanks, will try later to get it running on the Pi

Tim

**Comment by kamilfb** [comment]
hi @TLaren. any more luck?

**Comment by kamilfb** [comment]
Seems like Java on RPi is missing JavaFX support by default.

Found something on SO: http://stackoverflow.com/questions/36961054/can-javafx-be-used-on-raspberry-pi

Downloading the Gluon SDK and copying the jfxrt.jar to your JRE/JDK lib directory might be the solution - would you like to give it a try?

Also, there might be a way with using OpenJDK - take a look at #88

**Comment by acestu** [comment]
Hi Kamilfb, TLaren

You might find this page interesting, it has a version of java with FX for raspberry pi, you might have more luck with it:

http://chriswhocodes.com/

Thanks
Stuart

**Comment by TLaren** [comment]
Thanks for the support. Just have not had time to try your solutions. Tomorrow I will let you know how it worked.

Thanks again,

Tim

**Comment by kamilfb** [comment]
@TLaren any more luck with that? For future questions or comments, could you use https://github.com/eclipse/paho.mqtt-spy/issues/5 instead so that we have only one issue open for this?

**Comment by sova32** [comment]
> java -jar mqtt-spy-1.0.0.jar
Error: Could not find or load main class pl.baczkowicz.mqttspy.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
