### ISSUE TITLE
where is the 'jar' file

### ISSUE THREAD

**Issue by consolacion** [kamilfb/mqtt-spy#105]
Maybe it is just me, but the instructions say 'just click on the jar file in mqtt-spy'
I don't see any jar file anywhere in the many folders and subfolders of mqtt-spy.
I downloaded it, there is a folder called mqtt-development that has 6 subfolders such as 'mqtt-spy'  etc, but nowhere a jar file in sight

**Comment by kamilfb** [comment]
@consolacion , what are you trying to do?

**Comment by consolacion** [comment]
I am trying to install and use mqtt-spy. The wiki tells me that after download I should click  the 'jar' file, but there is no jar file.  In the mean time i found the "mqtt-spy-0.6.0........with dependencies.jar" file in another repositorie (I presume)  but that just wants to install files, whereas I understood that would open the application.

In other words, Just trying to use mqtt-spy but it is a mystery to me how. Followed the wiki with no results. Your help is much appreciated

**Comment by kamilfb** [comment]
@consolacion 
1) Go to "Wiki" -> "Downloads"
2) Download version 0.5.4 (mqtt-spy-0.5.4-jar-with-dependencies.jar)
3) Double click the JAR to start (assuming you've got appropriate version of Java installed)

**Comment by consolacion** [comment]
i will give that a try. I have 1.8
I see that is from where I did download the jar before. That just opens up and wants to install files
and so does version 0.5.4 :-(

**Comment by kamilfb** [comment]
What do you mean by "it wants to install files"? It will create a directory in your home folder so that you can save config and stats.

**Comment by consolacion** [comment]
apologies, I was not clear: it  will not run the application but opens  the archive managers window from where I can only extract files

**Comment by kamilfb** [comment]
@consolacion , have you followed https://github.com/kamilfb/mqtt-spy/wiki/GettingStarted?

what's the output of "java -version"?

**Comment by consolacion** [comment]
Yes I have. Have downloaded and installed 1.8, but I already see the problem. Java.com tells me I have 1.8 installed but the terminal : java -v tells me it is 1.7.  in spite of me  removing prior versions and restarting.
I presume that is where the problem is.
Thank you for your help, I think I  need to find the solution on the java side

**Comment by kamilfb** [comment]
@consolacion , yes, it looks like a java problem. Even though, go through the getting started guide and see how you can start mqtt-spy with a specific version of java, even if multiple are installed

**Comment by consolacion** [comment]
I had seen that indeed, will try. Thanks.
(I so dislike Java :-) )

**Comment by consolacion** [comment]
Sadly no avail. Have java 1.8_111 installed. is reported in my terminal with java -version, is  reported by java.com,
restarted computer, but the jar file will not execute but is opened in archive manager.
the only thing that changed is that before I would get a message  that it is an excutable... and then it would open in archive manager, and now it directly opens in archive manager.
As mqtt-spy  obviously works with many people, I  still suspect the problem is 'somewhere' in java, but currently I have no idea where.
nevertheless thanks for your help, not going to further bother you with java issues :-)

**Comment by consolacion** [comment]
OK solved, apparently due to the trouble before it probably didnt no better anymore than to 'open in archive'. Right click and 'open in java' did the trick
