### ISSUE TITLE
Topic supsciption

### ISSUE THREAD

**Issue by 8666** [kamilfb/mqtt-spy#106]
If I subscribe to something like

home/+/+/+

I do not get any data
but if I subscribe later to
home/+/+

I will get the data for topics like
home/room-temperature/Bedroom

in both tabs.

Why the second tab change the logic in the first one?

**Comment by kamilfb** [comment]
hi @8666, the project has now moved to Eclipse Paho - please use the new GitHub repo at https://github.com/eclipse/paho.mqtt-spy to raise any questions or issues. thanks
