### ISSUE TITLE
Initial Subscription not working

### ISSUE THREAD

**Issue by aidanruff** [kamilfb/mqtt-spy#107]
Hi

If I add a subscription (0.6.0 Beta) to a connection definition, then open the connection, the subscription doesn't work. So, say I subscribe to topic '#' to receive all traffic from the MQTT server, I see nothing coming in and can still add a subscription to '#'.

If I make a default subscription to '#' and click on "create tab", a tab is created for the subscription when I open the connection, but no messages are shown. If I right click on the tab and select "re-subscribe", it then works just fine and the messages are disapplayed.

Might just be me, but I can;t see what I'm doing wrong!

**Comment by kamilfb** [comment]
the project has now moved to Eclipse Paho - please use the new GitHub repo at https://github.com/eclipse/paho.mqtt-spy to raise any questions or issues. thanks
