### ISSUE TITLE
IOException when trying to connect with client-certificate

### ISSUE THREAD

**Issue by EugenNeufeld** [kamilfb/mqtt-spy#111]
Hi folks, 

i've been trying to connect to my mosquitto-broker at my localhost on port 8883 by using the "CA certificate and client certificat/key" mode in the security/TLS settings. I have also put in the rest of the TLS-settings. Now everytime  I try to connect to my (already running and correctly configured broker) mqtt-spy gives me the error message: "Invalid configuration parameters - IOException : DerInputStream.getLength(): lengthTag=125, too big".

I'd be very pleased if someone could give me hints for the solution.

Thanks

**Comment by kamilfb** [comment]
hi @EugenNeufeld - this repo is not active anymore. could you use https://github.com/eclipse/paho.mqtt-spy instead?
