### ISSUE TITLE
there must be a memory leak

### ISSUE THREAD

**Issue by Marwe** [kamilfb/mqtt-spy#113]
mqtt-spy is eating memory faster than you can produce chips.
In the attachment you can see the memory consumption logged in mqtt-spy via MQTT.
Only few minutes and all memory is used up.

Same thing observed with these versions:
mqtt-spy-0.5.3-jar-with-dependencies.jar
mqtt-spy-0.6.0-beta-b56-jar-with-dependencies.jar

I published the memory usage with this bash snippet: 
`while true ; do mosquitto_pub -t 'mqtt-spy/memoryusage' -m "$(ps -C "java -jar /path/to/mqtt-spy-0.6.0-beta-b56-jar-with-dependencies.jar" -o vsz=)"; sleep 1; done`

Maybe someone observes the same and has the possibility to track it down?

Thanks

**Comment by Marwe** [comment]
Upload of screenshots here did not work, see them there:
https://imgur.com/a/qDzCR

**Comment by Marwe** [comment]
The amount of different messages was roughly 20 in total with 1 Hz (10 messages/second), one value being plotted.

**Comment by kamilfb** [comment]
@Marwe , thank you for reporting this - this repo is not active anymore - could you use https://github.com/eclipse/paho.mqtt-spy instead? I will be happy to look into this futher

**Comment by kamilfb** [comment]
Using the other repo so closing.
