### ISSUE TITLE
Feature request: send retained msg using GUI

### ISSUE THREAD

**Issue by sticilface** [kamilfb/mqtt-spy#114]
I might be missing this, but i've had a good look.  

how do I set the QOS and retain flags for messages sent using the GUI? 

If it is not possible could this be added?

Great software btw:)

**Comment by kamilfb** [comment]
@sticilface , yes, you need to change the perspective. Window -> Change perspective -> Detailed

**Comment by sticilface** [comment]
OMG!  how did I not find that!  Thanks.  I googled it loads too... oops

Thank you

**Comment by kamilfb** [comment]
no problem @sticilface - happy spying... ;)
