### ISSUE TITLE
Last Will received data has unexpected value

### ISSUE THREAD

**Issue by DavidAntliff** [kamilfb/mqtt-spy#119]
mqtt-spy v1.0.0 on macOS Sierra.

If I set the Last Will data to "888" and re-establish the connection, then monitor the topic with a second instance of mqtt-spy, then a Force Quit on the original client will send the Last Will message to the broker, and it will be received by the subscribed second client. I see the message arrive but the data is not what I expect - it is two black diamonds with a white question mark inside each, and is most definitely not "888".

I couldn't find a way to display the raw data as bytes, or export it to a file, so I'm not sure what data values are actually received.

With all other received MQTT messages, I see the bytes as plain text, so I was expecting to see "888" in the receiving client's subscribed topic.

**Comment by kamilfb** [comment]
This repo has been archived. Could you raise this in https://github.com/eclipse/paho.mqtt-spy?
