### ISSUE TITLE
Double clicking the resize 'Topic' column pushes the 'Last Received' column off the screen

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kamilfb/mqtt-spy#19]
```
What steps will reproduce the problem?
1. Load up MQTT-SPY
2. Double click upon the column resizer for the 'Topic' column


What is the expected output? What do you see instead?

Expected is that the Topic column will resize to fit the content but all of the 
remaining columns remain visible. In practice, the Topic column does resize but 
then obscures the 'Last Received' column as per the attached image.


What version of the product are you using? On what operating system?

Living on the edge! - 0.1.3 beta (build 18) on Windows 7.


Please provide any additional information below.

Screenshot attached.

```

Original issue reported on code.google.com by `blakepe...@googlemail.com` on 17 Dec 2014 at 9:36

Attachments:
* [MQTT_SPY_Column_Resize_Double_Click.PNG](https://storage.googleapis.com/google-code-attachments/mqtt-spy/issue-19/comment-0/MQTT_SPY_Column_Resize_Double_Click.PNG)

**Comment by kamilfb** [comment]
This is how JavaFX works in the situation where the table doesn't have maximum size defined. If the table was to have fixed size, we wouldn't be able to see all the content. Leaving it as is.
