### ISSUE TITLE
Provide option to change font size

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kamilfb/mqtt-spy#30]
```
in order to better use desktop estate it would be nice to be able to adjust the 
font size used by MQTT-Spy
```

Original issue reported on code.google.com by `matt.br...@gmail.com` on 11 Feb 2015 at 12:42

**Comment by kamilfb** [comment]
As this can be achieved in FXML or the operating system, a decision was made not to implement it in the main code base. Please feel free to fork the repository and change it to meet your requirements.
