### ISSUE TITLE
Key Store Dialog does not support passwords for keystors

### ISSUE THREAD

**Issue by dobermai** [kamilfb/mqtt-spy#43]
When using self-signed certificates with Java keystores, there is no possibility to set a password for the keystore in mqtt-spy.

**Comment by kamilfb** [comment]
Hi Dominik. I'm planning to add more TLS/SSL options to version 0.4.0. Beta should be available in December.

**Comment by kamilfb** [comment]
This functionality should be now available in 0.4.0 beta

**Comment by kamilfb** [comment]
Available from 0.4.0 beta (build 4).
