### ISSUE TITLE
configuration file as a command line paramener

### ISSUE THREAD

**Issue by AlexBGoode** [kamilfb/mqtt-spy#51]
Hello

As for now, a configuration file is created and loaded from users home directory
Any chance to enable specifying the location of a configuration file during startup?
For example to make it portable and keep config files locally together with JAR file

**Comment by kamilfb** [comment]
Hi Alex,

Yes - that's already possible. I've just added a section to the 'Getting Started' wiki page.

If you are on Windows, you can do it on the command line or via a shortcut by specifying an additional parameter, for example:

java -jar  mqtt-spy-0.3.0-jar-with-dependencies.jar pl.baczkowicz.mqttspy.Main --configuration="C:\mqtt-spy\labs.xml"

Let me know if that's what you need.

**Comment by AlexBGoode** [comment]
Thanks, Kamil
It works well
