### ISSUE TITLE
Add support for Kura's payload format

### ISSUE THREAD

**Issue by darugnaa** [kamilfb/mqtt-spy#56]
Hi Kamil,
I was thinking about implementing a custom payload decoder/encoder to support [Kura's payload format](https://www.eclipse.org/kura/).  
However I can't fully understand where and how the incoming messages processing happens.
Could you share some hints to point me in the right direction? I saw a "Custom" menù item that is actually disabled, so I think there's a way to "plug" new decoders.
Thanks.

**Comment by kamilfb** [comment]
Hi,

One way to do that is to define a custom formatter. Go to Menu -> Window -> Open View -> Formatters and add a new script-based formatter. Then you can edit the sample javascript to do what you need.

Once you've got your formatter defined, you can then select it for a connection.

Let me know how you get on with that...

**Comment by kartben** [comment]
That would be a great addition, yes!
@kamilfb , since the Kura payload is actually encoded using Protocol Buffers, will that be possible for the provided script to import an external protobuf JS library from, say, a CDN?

**Comment by kamilfb** [comment]
All sounds possible I think! I haven't used Kura before though, but I'm very happy to help on that. What would help:
- have public Kura running somewhere and publishing over MQTT
- get a sample Java app receiving those updates and formatting it right
- then we can easily add it to mqtt-spy
darugnaa, kartben, is it something you could assist with?

**Comment by darugnaa** [comment]
I was thinking about a Java solution (some sort of plugin maybe?).
I'll dig a bit into javascript formatters and see what I can get.

**Comment by kamilfb** [comment]
To help me better understand what we are trying to achieve, could you post a sample of how you would use the custom payload encoder/decoder? Could you attach an example of how the message looks like when it is encoded, and how it could look like when decoded?

**Comment by kartben** [comment]
I shall do that!

Le sam. 30 janv. 2016 01:18, Kamil Baczkowicz <notifications@github.com> a
écrit :

**Comment by kartben** [comment]
Hi @kamilfb – is that helpful? https://gist.github.com/kartben/a07c6f5cb1aa3ad6473d

**Comment by kamilfb** [comment]
Yes - thank you @kartben! Have you also got a live feed of Kura's MQTT messages that I could test with? E.g. iot.eclipse.org?

**Comment by kartben** [comment]
It's not "live", but there's a few Kura gateways that do post messages on "$EDC/#" root topic once in a while. Now that I think about it, I realize that the payload can also be gzipped, if that's what's configured in the Kura settings. 

So I guess you have now two ways for testing:
- either listen to iot.eclipse.org, and once in a while it's likely you may see messages with a gzipped payload (with protobuf in it)
- test with my non-gzipped dump, which you can easily re-publish on a topic of your choice

**Comment by kamilfb** [comment]
@darugnaa @kartben I believe I made some progress :)

Before formatting:
![before](https://cloud.githubusercontent.com/assets/8521600/12833074/14ea9bf8-cb96-11e5-8c22-d356a998404b.png)

After formatting:
![after](https://cloud.githubusercontent.com/assets/8521600/12833081/1f664adc-cb96-11e5-86b2-bbdd822c5734.png)

Is that the sort of thing you are after?

**Comment by kamilfb** [comment]
You can try it now with mqtt-spy 0.5.0 beta build 4. Just follow the example in the Formatting wiki page to set up a new formatter and the use it.

**Comment by kamilfb** [comment]
@darugnaa @kartben mqtt-spy 0.5.0 beta build 7 has got a built-in Eclipse Kura formatter. Also, it converts the payload automatically to JSON and does pretty formatting on it. Could you confirm it is working as expected?
