### ISSUE TITLE
Save graphs at regular intervals

### ISSUE THREAD

**Issue by acoxall** [kamilfb/mqtt-spy#60]
It would be great to be able to save the graphs that mqtt-spy produces, at regular intervals.
These could then be published to a web page.

**Comment by kamilfb** [comment]
Hi Al. Thanks for raising this. Sounds very do-able. I'll look into it soon.

**Comment by kamilfb** [comment]
Could you also describe the conditions under which it starts running slowly, e.g. what you do and how it behaves?

**Comment by acoxall** [comment]
I cant really describe this as an issue since it is most likely to be caused by the low spec PC (32 bit single core) under Win7.

 

I have the PC and 2 RPis running Mosquitto / Paho on each.

The systems send about 5 topics each, every 10 seconds from weather, boiler (temp) and electricity monitors

 

Javaw.exe is showing about 49% CPU usage all the time on the PC which is running SPY. I'm also running a java program to collect the electricity data so I cant be certain which is taking up the CPU.

My other programs total about 51% , so my PC is maxed out.  So at least half of the performance issue is NOT down to SPY.

 

I have a set of graphs for each system.  These are working fine for my purposes, but because I'm using 100% CPU, its hard to adjust them.

 

I think I need to move this over to a bigger PC

 

Cheers,

 

Al

**Comment by kamilfb** [comment]
Al, have a look at this one: tinyurl.com/mqtt-spy-download/mqtt-spy-0.5.0-beta-b1-jar-with-dependencies.jar and tell me if that's any good. There is a new item in the "Options" button on the chart window. Once you do Save as, it enables auto-export options.

**Comment by acoxall** [comment]
Hi Kamil,

 

This is working really well and is exactly just what I wanted!!!  It is already up on my in-house web-site.

 

Thanks so much for this….It was just what I needed

 

Al

**Comment by kamilfb** [comment]
I'm glad it works fine! Would you consider making a small donation to UNICEF at https://www.justgiving.com/mqtt-spy? Cheers!

**Comment by acoxall** [comment]
No problem, I will do that now  and thanks again

 

Al

**Comment by kamilfb** [comment]
Awesome! Thank you for your support!
