### ISSUE TITLE
Multiple connections support - enhancement request

### ISSUE THREAD

**Issue by tomvitez** [kamilfb/mqtt-spy#61]
Can you support/manage multiple client connections today in mqtt-spy-daemon? The reason I ask is I'm wanting to use the deamon to put load on my MQTT broker to simulate 1000's of simultaneous TCP clients. /Tom

**Comment by kamilfb** [comment]
Hi! Apart from creating multiple connections, what are your requirements for publications and subscriptions? Any specific messages?

**Comment by tomvitez** [comment]
I'm trying to simulate real system load so I will have some connections publishing to topics and many more connections subscribed to these topics. The other option from using your deamon is for me to write Grinder scripts that call the Paho Java client API's directly and have some vUsers (threads) simulating connections to publish and others to subscribe... I hope that answered your question?

**Comment by kamilfb** [comment]
Hi Tom. It is possible, but wouldn't be very practicable in its current form. I'm looking into creating something that would allow specifying groups of daemon instances, each group containing a number of instances required and a template configuration. Then the scripts would be automatically provided with an instance ID so that scripts can be used as templates too. Does it make any sense? ;)

**Comment by tomvitez** [comment]
Yes this makes sense to me and would be very valuable. In the mean time, you say it is possible in its current form to accomplish what I'm after. Have you or anyone you know done something similar and would be willing to share some sample(s)?

**Comment by kamilfb** [comment]
Hi @tomvitez! 

I decided to do it "properly" and last night created mq-spy-swarm (https://github.com/kamilfb/mq-spy/tree/master/mq-spy-swarm).

You can download the jar from: http://baczkowicz.pl/mq-spy/download/mq-spy-swarm-0.0.1-beta-b7-jar-with-dependencies.jar

Then run "java -jar mq-spy-swarm-0.0.1-beta-b7-jar-with-dependencies.jar config.xml".

Sample config: https://github.com/kamilfb/mq-spy/blob/master/mq-spy-swarm/src/test/resources/test_configurations/basic-mqtt-swarm-configuration.xml


The script that is used is here: https://github.com/kamilfb/mq-spy/blob/master/mq-spy-swarm/src/main/resources/sample-swarm-publish.js

Let me know if that's the sort of thing you are after.

**Comment by tomvitez** [comment]
You are a machine! THANK YOU... I will give it a whirl and let you know how it works for me. Very much appreciated.

**Comment by kamilfb** [comment]
No problem - if something needs improving, let me know.

**Comment by kamilfb** [comment]
Hi @tomvitez - have you got any feedback on that? Shall we close the issue?

**Comment by tomvitez** [comment]
Hi Kamil, Sorry for the tardy response I ended up delegating the evaluation of swarm to a colleague on the project. He tried to get things going but had issues connecting with a signed SSL certificate. Cannot use any properties – e.g. UserCredentials and SSL – other than those specified on “mq-spy-swarm-configuration.xsd”. See exception in the log file attached...
[mq-swarm-log.txt](https://github.com/kamilfb/mqtt-spy/files/161646/mq-swarm-log.txt)

**Comment by kamilfb** [comment]
Hi @tomvitez - looks like your XML tags are not right. It is important to keep the correct sequence of XML tags. See examples:

https://github.com/kamilfb/mqtt-spy/wiki/DaemonConfiguration

UserCredentials is defined just after ClientId, and SSL just after the KeepAlive and before MessageLog.

For more info see MqttConnectionDetails in https://github.com/kamilfb/mqtt-spy/blob/development/mqtt-spy-common/src/main/resources/mqtt-spy-common.xsd

**Comment by kamilfb** [comment]
mq-spy renamed to msg-spy - please see the other repo for this issue.
