### ISSUE TITLE
Request: Custom formatter for JSON payloads

### ISSUE THREAD

**Issue by TotallyInformation** [kamilfb/mqtt-spy#65]
Hi,

Many, many thanks for creating this tool. It is really helpful.

One thing I find myself doing though is often copying the data payload and pasting to Notepad++ then formatting as JSON so that I can make sense of data.

It would be great if we could have a formatter that would pretty-print JSON in the data part of the "Subscriptions and received messages" section of the display.

I don't suppose I'm the only person commonly using JSON data with MQTT so I would think that this would be really helpful.

Regards, Julian.

**Comment by kamilfb** [comment]
Thanks for raising this Julian - I'll look into it.

**Comment by kamilfb** [comment]
Hi @TotallyInformation,

I've created a new beta build for you to try: http://baczkowicz.pl/mqtt-spy/download/mqtt-spy-0.5.0-beta-b7-jar-with-dependencies.jar

Let me know if that is any good.

**Comment by TotallyInformation** [comment]
Sorry, missed the message. Trying now.

**Comment by TotallyInformation** [comment]
Yay! That's great - many thanks for that, it's going to make a big difference. And you've fixed quite a few formatting issues I've always had on Windows, especially when moving between monitors with different settings.

**Comment by kamilfb** [comment]
Many thanks @TotallyInformation for the feedback - happy to hear you like it. Would you consider making a small contribution to UNICEF at https://www.justgiving.com/mqtt-spy/ ? Any other problems - let me know!

**Comment by TotallyInformation** [comment]
Contribution done. Thanks for reminding me to do that. I also gave you a mention on the [Google Group for Node-Red](https://groups.google.com/forum/#!forum/node-red), a flow-based tool aimed largely at IoT so there are a lot of heavy MQTT users there. NR is developed as an open source tool by IBM. A lot of us use JSON payloads for IoT so the formatter is really useful.

**Comment by kamilfb** [comment]
Awesome! Thank you! :)
