### ISSUE TITLE
When resizing mqtt windows to lower size, right buttons are no more available

### ISSUE THREAD

**Issue by lnun13** [kamilfb/mqtt-spy#66]
Hi.
Here is an issue I saw:

Launch mqqt-spy application.
Set it as full screen then restore original size.
Defect: right buttons may have desappear (depending on original size).
If you do not want anymore full screen, you need to restart application.

By right button, I mean:
- publish
- subscribe
- tools,
-search 
- message navigation 
![mqtt](https://cloud.githubusercontent.com/assets/17641339/13525505/a474580a-e201-11e5-9e8d-7d681efeaf5d.png)

**Comment by kamilfb** [comment]
Hi. Which version of mqtt-spy and Java are you using?

**Comment by kamilfb** [comment]
Hi @lnun13! 

I've just tried the same version of mqtt-spy on Java 8 Update 73, on Windows 7, and I can't reproduce your problem in any way.

I believe to create this problem you simply click on "Maximise" and "Restore" buttons for the mqtt-spy window? Which OS are you on?

Could you update to Java 8 Update 73 and retry?

**Comment by kamilfb** [comment]
Hi! Thanks for confirming. I was also able to reproduce it on Windows 10. I'll look into it!

**Comment by kamilfb** [comment]
What causes this issue is when you select a non-default text size on Windows. The default is Smaller (100%). If you use Medium (%125) or Large (%150) then you will experience the issue. 

**Workaround: change text size to Smaller (100%) in Control Panel -> All Control Panel Items -> Display.**

**Comment by kamilfb** [comment]
Could you try the latest beta and see if that's any better now? 
http://tinyurl.com/mqtt-spy-download/mqtt-spy-0.5.0-beta-b15-jar-with-dependencies.jar

**Comment by lnun13** [comment]
I confirm that with this release, problem is solved!
Thanks.

**Comment by kamilfb** [comment]
Thanks for confirming! Cheers
