### ISSUE TITLE
Subscription that have been defined in connection setting, is not subscribed until a re-subscribe is performed

### ISSUE THREAD

**Issue by lnun13** [kamilfb/mqtt-spy#67]
Hi.

I created a connection with several topics subscriptions and when I connect to this connection, all thoses topics are in fact not subscribed: title is in italic font and messages of related topics are not displayed.
As a result, to have the topics declared as subscribed in connection parameters truly functional, you need to re-subscribe to all those topics.

Thanks.
Regards

**Comment by kamilfb** [comment]
Hi. Which version of mqtt-spy and Java are you using?

**Comment by kamilfb** [comment]
In configuration for your connection, have you selected "Auto-subscribe when opened" (the "Other" tab)?

**Comment by kamilfb** [comment]
No problem - I'm glad it works. It's a good suggestion so I'll add it to my list to consider in the future. Are you happy to close this issue now?
