### ISSUE TITLE
On connection list window, it is not possible to increase area for connection parameters

### ISSUE THREAD

**Issue by lnun13** [kamilfb/mqtt-spy#68]
Hi.

When I open connection list to edit parameters, I wanted to see all parameters of my subscribed topics at the same time. So I tried to increase the size of area allocated to parameters but it is not possible, even if I set windows to full screen (additionnal size is then used to the connection list itself which is, for me, less relevant.)
It would be nice to have larger area for connection parameters check.
![sans titre](https://cloud.githubusercontent.com/assets/17641339/13565575/2553c6b2-e451-11e5-9e06-6655297468c1.png)

enclosed the picture for better understanding.

mqtt-spy: 0.4.0 (build 12)
java v8 update 73 (build 1.8.0_73-b02)
Windows 7 pro SP1

**Comment by kamilfb** [comment]
Thanks for raising - I'll look into it...

**Comment by kamilfb** [comment]
Could you try the latest beta and see if that's any better now? 
http://tinyurl.com/mqtt-spy-download/mqtt-spy-0.5.0-beta-b15-jar-with-dependencies.jar

**Comment by lnun13** [comment]
Hi.

I just tried. I confirm this solve the issue :-)
Thanks a lot for this good tool.

**Comment by kamilfb** [comment]
Thanks for confirming! Ta
