### ISSUE TITLE
In one case, it is no more popssible to add a topic subscription unless connection and tabs are closed and reopened

### ISSUE THREAD

**Issue by lnun13** [kamilfb/mqtt-spy#69]
Reproduced on windows 7 Pro with mqtt spy 0.5.0 beta build 15.

Subscribe to several topics so that all topic tabs cannot be displayed simultaneously. (topic can have long name to have wider size)
Using arrow on right side of subscribed topic tab, select last subscribed topic.
Now, you cannot access anymore  to "New" tab to subscribe to topic except closing/ restoring connection/tabs that will lose your mqtt messages history.

This is due to the fact that new is not available in tab selection opened with arrow click, and that navigation is disabled on tabs.

**Comment by kamilfb** [comment]
There is a workaround to use a keyboard shortcut: Ctrl+Shift+S. Will be fixed in 0.5.0. Thanks for reporting!

**Comment by kamilfb** [comment]
Fixed in 0.5.0 - could you try it out?

**Comment by lnun13** [comment]
Hi.
I confirm. "New" is now always enabled.
Thanks for your reactivity.
Regards.

**Comment by kamilfb** [comment]
Cool - thanks for confirming! Cheers
