### ISSUE TITLE
problem saving scripts

### ISSUE THREAD

**Issue by gatovelho** [kamilfb/mqtt-spy#70]
Hi,
thank you very much for sharing mqtt-spy.

I am no software type so I may be saying something very wrong. Hope not.

I am using "mqtt-spy-0.4.0-jar-with-dependencies "on windows 10 home (32 bits)

an d I am having problems with directories . 
Notably (but not only)  I am not being able to save scripts. They just vanish.
Had to create a few of them them by hand. 
The demon also fails creating files even the basic default script.

Adding some log below.

Best regards,
CS

2016-04-01 08:40:54,475 ERROR [JavaFX Application Thread     ] [SpyUncaughtExceptionHandler   ]  - Thread Thread[JavaFX Application Thread,5,main] failed with java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
....(removed)
...
	... 44 more
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(Unknown Source)
	at pl.baczkowicz.mqttspy.ui.NewPublicationController.createScriptFromMessage(NewPublicationController.java:873)
	at pl.baczkowicz.mqttspy.ui.NewPublicationController.saveAsScript(NewPublicationController.java:846)
	at pl.baczkowicz.mqttspy.ui.NewPublicationController.saveCurrentAsScript(NewPublicationController.java:804)

**Comment by kamilfb** [comment]
Hi. Thanks for reporting this issue. I've managed to reproduce it. Will try to get a fix for that soon.

**Comment by kamilfb** [comment]
Fixed in 0.5.0 - could you try it out?

**Comment by gatovelho** [comment]
Thank you. 
I will submit feedback after doing some work

**Comment by gatovelho** [comment]
Did some testing.
It has improved, but still has some problems.
the good: it now looks at default directory for publishing scripts. Finds the script if it is there.
the bad: is not able to "publish from script" when Topic is empty, even if has the Topic embedded in the script. If we put even a space in the topic, then it gets published.
also bad: does not look for the scripts in the "directory with publication scripts" (set by hand). Those scripts however do show up -and execute correctly- after refreshing "script publications" windows and starting them from there by double-clicking.
There are some odd interactions but methinks the may get fixed after this issue is addressed.
Thank you again for your support.

**Comment by kamilfb** [comment]
Many thanks for the feedback. I will look into it further...

**Comment by gatovelho** [comment]
Just ocurred to me: strictly speaking, this topic should be considered closed. I found no problems when saving scripts in the new version 050. 
I could open a new issue on the difficulties reported above if you think that is the proper way.
Regards

**Comment by kamilfb** [comment]
Hi. Sounds like a good plan! I'll close this one as fixed and if you don't mind, please open new issue(s) for the other problem(s). Cheers!
