### ISSUE TITLE
How do you build this project?

### ISSUE THREAD

**Issue by pfurbacher** [kamilfb/mqtt-spy#73]
I'm very interested in this project, mainly from the perspective of the JavaFX UI.

I cloned the "development" branch, and before that the "master" branch.

Neither will build successfully. 

Here's what I have done, based on the apparent order of dependencies in the various projects. But I have had no success, primarily due, I think, to not being able to access the Paho snapshot, version 1.0.3-20151116.050526-315. But that may not be the entire problem.

1. cd spy-common; mvn clean install  -> this seems to succeed
2. cd spy-common-ui; mvn clean install -> also okay.
3. cd matt-spy-common; mvn clean install -> trouble starts here

Here is the last step's output, elided to save some space, and lines wrapped for easier reading:

```
mqtt-spy-common pf$ mvn clean install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building mqtt-spy-common 0.1.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for 
org.eclipse.paho:org.eclipse.paho.client.mqttv3:jar:1.0.3-20151116.050526-315 
is missing, no dependency information available
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.101s
[INFO] Finished at: Mon Apr 04 09:30:47 EDT 2016
[INFO] Final Memory: 12M/220M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mqtt-spy-common: 
Could not resolve dependencies for project pl.baczkowicz.mqttspy:mqtt-spy-common:jar:0.1.0: 
Failed to collect dependencies for [pl.baczkowicz.spy:spy-common:jar:0.2.0 (compile), 
org.eclipse.paho:org.eclipse.paho.client.mqttv3:jar:1.0.3-20151116.050526-315 (compile), 
com.google.protobuf:protobuf-java:jar:2.6.1 (compile), 
 org.eclipse.kura:org.eclipse.kura.core.cloud:jar:1.0.6 (compile), 
org.eclipse.kura:org.eclipse.kura.core:jar:1.0.6 (compile), 
org.eclipse.kura:org.eclipse.kura.api:jar:1.0.6 (compile), 
org.eclipse.moquette:moquette-broker:jar:0.7 (compile), 
org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:jar:0.9.0 (compile), 
org.jvnet.jaxb2_commons:jaxb2-commons-lang:jar:2.4 (compile), 
org.jvnet.jaxb2_commons:jaxb2-basics-runtime:jar:0.9.4 (compile), 
org.apache.commons:commons-lang3:jar:3.4 (compile), 
junit:junit:jar:4.11 (test), cglib:cglib-nodep:jar:2.1_3 (test), 
org.jmock:jmock-legacy:jar:2.5.1 (test), org.objenesis:objenesis:jar:1.0 (test)]: 
Failed to read artifact descriptor for
 org.eclipse.moquette:moquette-broker:jar:0.7: 
Failure to find org.eclipse.moquette:moquette-parent:pom:0.7 in 
https://repo.eclipse.org/content/repositories/paho-releases/ was cached in the local 
repository, resolution will not be reattempted until the update interval of 
Eclipse Paho Repo has elapsed or updates are forced -> [Help 1]
```

Following the same steps for the "master" branch results in similar problems. 

Have you done a clean install (Docker like) for your repository on a clean machine and rebuilt recently?

Have you customized your .m2/settings.xml file in such a way that it "just works" on your development machine but won't anywhere else?

Also, how do you structure these projects in Eclipse?

Perhaps a wiki page on "Getting started for developers" that covers these issues?

Thanks.

Comment updated to include version info: 

$ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

OS X El Capitan version 10.11.4 (15E65)

**Comment by kamilfb** [comment]
See the dev branch - added a top-level POM and updated some of the dependencies. Any better?

**Comment by pfurbacher** [comment]
Yes, much better. Nice UI! Now I have to learn more about MQTT. 

I'm thinking this issue can be closed.

Thanks.

**Comment by kamilfb** [comment]
Thanks @pfurbacher for the feedback. If you find it useful, please consider making a small contribution to UNICEF at https://www.justgiving.com/mqtt-spy/
