### ISSUE TITLE
Messages in a list

### ISSUE THREAD

**Issue by kamilfb** [kamilfb/mqtt-spy#74]
The message browser pane only allows to see one message at a time for a given topic or group of topics (see below):
![12 - first pub received - selection](https://cloud.githubusercontent.com/assets/8521600/14701048/01ef3b94-079b-11e6-8061-02c8cb6da855.png)

In order to see messages as a list, you have to perform a search (by clicking on the search button shown above), and enable auto-refresh (see below):
![13 - search](https://cloud.githubusercontent.com/assets/8521600/14701072/3471fd4a-079b-11e6-89f4-b4cbf6246bc9.png)

Ideally, this kind of list view would be available from the subscription/message browser pane rather than having to do a search.

**Comment by bhaskar001** [comment]
nice but can we find the packet loss and end to end delay by this tool ?

**Comment by kamilfb** [comment]
@bhaskar001, could you explain what you mean by packet loss & e2e delay?

**Comment by SuperTango** [comment]
This is cool, and would be great on the subscription page along with the auto-refreshing to provide a useful realtime list view.

**Comment by kamilfb** [comment]
Hi @SuperTango, have you tried version 0.5.4 and the multi message layout?

**Comment by SuperTango** [comment]
Hi @kamilfb Yes, I have.  It's ok, but the reason I like the list view is that I can see many messages and quickly scan over what's in each.
