### ISSUE TITLE
Warning: "The plugin is configured to use catalogs and strict at the same time."

### ISSUE THREAD

**Issue by pfurbacher** [kamilfb/mqtt-spy#75]
In the Eclipse Error Log, I'm seeing the following warning multiple times when Maven rebuilds: 

> The plugin is configured to use catalogs and strict at the same time.
> Using catalogs to resolve schema URI in strict mode is known to be problematic and may fail.
> Please refer to the following linkfor more information:
> https://github.com/highsource/maven-jaxb2-plugin/wiki/Catalogs-in-Strict-Mode
> Consider setting <strict>false</strict>

To resolve this warning, you would add `<strict>false</strict>` as shown in the following `pom.xml` snippet:

```
<plugin>
    <groupId>org.jvnet.jaxb2.maven2</groupId>
    <artifactId>maven-jaxb2-plugin</artifactId>
    <version>0.12.0</version>
    <executions>
        <execution>
            . . .
            <goals>. . .</goals>
            <configuration>
                . . .
                <strict>false</strict> 
                <catalogs>
                    . . .
```

This warning occurs when Eclipse automatically builds/updates the `pom.xml` file in the following projects:
- mqtt-spy
- mqtt-spy-common
- mqtt-spy-daemon

There is no `<catalogs>` element in `spy-common`; hence, no warning.

**Comment by kamilfb** [comment]
Thanks for reporting this! I'll look into it.

**Comment by kamilfb** [comment]
That should be in the dev branch now - could you confirm it is working as expected?

**Comment by pfurbacher** [comment]
Looks like it is fixed.

**Comment by kamilfb** [comment]
Cool - thank you!
