### ISSUE TITLE
How can I use JSONPath on Charts?

### ISSUE THREAD

**Issue by AngeloBestetti** [kamilfb/mqtt-spy#76]
I didn´t see any info about it.

I´m getting this payload:
{"DeviceID":"68ce469e-4924-433b-b512","DeviceName":"ISS - International Space Station","Velocidade":27623.126303018,"Altitude":407.89249690649,"Latitude":50.955977913119,"Longitude":132.87471342574}

I´m trying to get the "Velocidade" using $.Velocidade but is not generating any line on the chart.

**Comment by kamilfb** [comment]
Hi! See the attached picture. Right click on the series and then Edit.

![screenshot at 2016-05-16 22 06 16](https://cloud.githubusercontent.com/assets/8521600/15303977/9ce38c24-1bb2-11e6-8024-00db68ceeefb.png)

Let me know if that's any good.

**Comment by AngeloBestetti** [comment]
![mqttspy](https://cloud.githubusercontent.com/assets/4291962/15322540/e25e11c8-1c13-11e6-80b2-05358858cb52.png)

**Comment by AngeloBestetti** [comment]
Looks like it´s not evaluating the decimal values, also the "Delete" button is disabled.

**Comment by kamilfb** [comment]
Hi. Is that on a public broker so that i can rest? Could you do edit series and attach screenshot?

**Comment by AngeloBestetti** [comment]
Yes I can do Edit, no the broker is private, but I will create a credentials for you.Do you mind give me some email to send the credentials?

**Comment by kamilfb** [comment]
Hi @AngeloBestetti - please send them to kamil.baczkowicz@gmail.com - cheers!

**Comment by kamilfb** [comment]
Fixed the delete button issue in 0.5.1. BTW - are you on Twitter? We could discuss the JSONPath issue...

**Comment by AngeloBestetti** [comment]
@angelobestetti

Em qua, 1 de jun de 2016 às 18:49, Kamil Baczkowicz <
notifications@github.com> escreveu:

**Comment by AngeloBestetti** [comment]
It´s working now, I made a mistake trying to create the chart from the topic instead of creating from Message Summary Message.
