### ISSUE TITLE
message is not escaped when saving as script

### ISSUE THREAD

**Issue by ColdFireIce** [kamilfb/mqtt-spy#77]
Hi,

when I save the following message as a script, the quotes are not correctly escaped and thus the script is not working:

topic: `test/set/foo/height`
payload: `{"val":92}`
"save current message as script"
`mqttspy.publish("test/set/foo/height", "{"val":92}", 0, false);`

I thing this will be a quick fix, but I ran across it, so I thought I should report it.

Thanks for this great program!

Greetings

**Comment by kamilfb** [comment]
Hi. Many thanks for reporting it. I'll try to fix it for version 0.5.1.

**Comment by kamilfb** [comment]
This is now available in 0.5.1. Let me know if you find any further issues!
