### ISSUE TITLE
Feature Request - configurable Ping rate

### ISSUE THREAD

**Issue by jckruege** [kamilfb/mqtt-spy#78]
I'm new to MQTT and this tool is just what I was looking for.  Based on the traffic observed in Wireshark, it appears the Ping interval from MQTT-SPY to the broker is fixed at 1 minute. Although I could filter out Ping Requests and Ping Responses in Wireshark, it would be nice if the Ping rate was configurable; perhaps default to the existing 1 minute, but configurable from 1 minute to 60 minutes.

**Comment by kamilfb** [comment]
Hi. Have you tried configuring the MQTT keep alive interval? The default is 60 seconds I believe.

**Comment by kamilfb** [comment]
To edit the keep alive, go to your connection settings and select the Connectivity tab. If you can't see the keep alive parameter there, select the Detailed configuration mode (perspective).

**Comment by kamilfb** [comment]
Hi @jckruege - have you had any luck configuring this?
