### ISSUE TITLE
How to execute MQTT Spy on windows machine without Dos in a box window

### ISSUE THREAD

**Issue by SteveQuinn1** [kamilfb/mqtt-spy#79]
Hi,

I am using .bat file to cast the necessary runic incantations and execute the app.

java -jar mqtt-spy-0.6.0-beta-b33-jar-with-dependencies.jar

The problem is it leaves a dos box with what looks like debug information hanging around. Is there anyway I can configure my set up so all I need to do is double click something?

BTW. Excellent piece of software.

More of a question than bug.

Regards

Steve

**Comment by kamilfb** [comment]
Hi,

If you have Java installed, you can just double click on the jar to start it.

Alternatively you can also create a shortcut to the jar file to pass in parameters if you need do.

If you go the .bat file route, you are always going to see the command line box.

If you haven't seen it yet, check out the getting started wiki - https://github.com/kamilfb/mqtt-spy/wiki/GettingStarted

Let me know if it helped.

Kamil

**Comment by SteveQuinn1** [comment]
Hi Kamil,

I appreciate the quick reply.

You are of course quite right, if I double click it runs. I just didn't occur to me to try this (even after reading the getting started Wiki) since the .jar file types on my PC install have no association with them, I assumed they wouldn't execute.

Thank you for your help

Best Regards

Steve

**Comment by kamilfb** [comment]
No problem! I'm glad it's working now.
