### ISSUE TITLE
Problem creating formatters

### ISSUE THREAD

**Issue by jpleblanc** [kamilfb/mqtt-spy#84]
I have installed both the 0.5.1 (build 44) and the 0.6 beta version and have not been successful in installing a formatter.  When selecting the menu option, it is going nowhere and not allowing me to define a new converter.  

I am trying to read the messages coming from the Kura Heater example.  They are arriving encrypted at the MQTT server.  Even when using the Eclipse Kura setting it does not resolve the decryption of the messages.

Can you help?

Thanks,

Jean Pierre

**Comment by kamilfb** [comment]
Hi - thanks for reporting. I've managed to reproduce the issue. Have you tried version 0.5.0?

**Comment by kamilfb** [comment]
Could you try the latest beta -  0.6.0 beta (build 46)?

**Comment by kamilfb** [comment]
This fix is now also available in release 0.5.2.
