### ISSUE TITLE
Kura formatter no longer works

### ISSUE THREAD

**Issue by nicolaMaza** [kamilfb/mqtt-spy#86]
**In the "Subscription and received messages" tab (0.5.1 build 44) :**
If you choose the option _Tools **->** Formatting **->** Eclipse Kura_ the payload does not change.

This feature worked for me in the older **0.5.0 build 22**

**Comment by kamilfb** [comment]
Hi. Thanks for reporting this. There is a known issue with version 0.5.1 - see https://github.com/kamilfb/mqtt-spy/issues/84 & https://github.com/kamilfb/mqtt-spy/wiki/Changelog. Could you try the latest beta and see if that resolves the problem?

**Comment by nicolaMaza** [comment]
Yes, the 0.6.0-beta build 46 fix the issue.
Next time i will read the known issue page before posting :)
Nicola

**Comment by kamilfb** [comment]
No problem - thanks for confirming! :)

**Comment by kamilfb** [comment]
This fix is now also available in release 0.5.2.
