### ISSUE TITLE
Packaging of binaries

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kamilfb/mqtt-spy#9]
```
At the moment mqtt-spy is a jar file, in order to run it you need Java 8 
installed.

It would be much easier if you could provide binaries using the JavaFX Native 
Packaging 
(https://blogs.oracle.com/talkingjavadeployment/entry/native_packaging_for_javaf
x)

Thanks,
Christian

```

Original issue reported on code.google.com by `m...@christiangoetz.net` on 10 Sep 2014 at 3:09

**Comment by kamilfb** [comment]
For now, decided not to implement this, as it brings a lot of additional work with each release, and the benefits don't necessary outweigh the drawbacks. Happy to reopen when time allows.
