### ISSUE TITLE
Message Content Chart: JSONPath: Value Expression - NumberFormatException

### ISSUE THREAD

**Issue by NicolSpies** [kamilfb/mqtt-spy#92]
### Message content chart Series

Value expression for JSON paths that are **3 levels deep** e.g. $.level1.level2.level3, returns the value encapsulated in square brackets e.g. [123.456]. 

This throws a **java.lang.NumberFormatException: For input string: "[123.456]"** Series Error

**Comment by kamilfb** [comment]
Hi @NicolSpies, could you attach the JSON document and the JSON expression you are testing with?

**Comment by NicolSpies** [comment]
[json doc.txt](https://github.com/kamilfb/mqtt-spy/files/388348/json.doc.txt)

JSON expresssion: $.*.daily.daily

The JSON expression returns 984.567 testing the JSON and expression on this URL:   https://jsonpath.curiousconcept.com/

**Comment by kamilfb** [comment]
The problem is in the "*" - it's a special character in JSONPath. Can you change it to a proper name?

**Comment by NicolSpies** [comment]
JSON special caracters are :

 \b  Backspace (ascii code 08)
\f  Form feed (ascii code 0C)
\n  New line
\r  Carriage return
\t  Tab
\"  Double quote
\  Backslash character

"*" not a special character, hence the comment that the correct value was returned when tested with JSON expression validator.

I will be able to modify my IOT Node to publish only text and numeric JSON keys :smile:

**Comment by kamilfb** [comment]
Hi @NicolSpies - I think there are some additional JSONPath special characters: http://goessner.net/articles/JsonPath/

I agree - best to modify your IOT Node :)

**Comment by NicolSpies** [comment]
Apologies, you are correct, wildcard is special character. I will modify my Node. Thanks for checking.
