### ISSUE TITLE
Unable to subscribe to a topic in the GUI once it has been subscribed to using a script

### ISSUE THREAD

**Issue by blakepercy** [kamilfb/mqtt-spy#93]
I am using the brilliant test automation feature of MQTT Spy but when I have subscribed to a topic within a test script then I am not able to subscribe to the same topic using the GUI:

Topic subscribed to in the script:
    mqttspy.subscribe("/UK/SIMSM/publication/model", 0);

Error reported by the GUI:
![spybug](https://cloud.githubusercontent.com/assets/13079894/17363253/3342c238-5971-11e6-9e63-648c25d31026.png)

**Comment by kamilfb** [comment]
Could you try the latest beta? http://tinyurl.com/mqtt-spy-download/mqtt-spy-0.6.0-beta-b52-jar-with-dependencies.jar

**Comment by blakepercy** [comment]
Tested against 0.6.0 beta 52 and verified as resolved.
