### ISSUE TITLE
Documentation: Scripting Subscriptions

### ISSUE THREAD

**Issue by ddeletic** [kamilfb/mqtt-spy#94]
The Subscriptions Scripting page could be expanded with more details. A couple of issues I came across so far are:
- explaining how to tie a script to a subscription (there is no way to do it on the connection tab, only through Configuration Panel - which wasn't immediately obvious).
- how to write a persistens Subscriptions script that wouldn't finish after running onMessage() once.

**Comment by kamilfb** [comment]
@ddeletic, I've updated the wikis to address your first point: https://github.com/kamilfb/mqtt-spy/wiki/Scripting & https://github.com/kamilfb/mqtt-spy/wiki/ScriptingSubscriptions

**Comment by kamilfb** [comment]
@ddeletic, for your second point - could you explain your use case further? What would you use this continuously running script for?

**Comment by ddeletic** [comment]
Thank you for the quick response. 

As for the second point, I'm trying to write a script that would transfer a file to the remote device in several chunks. The idea is for the script to publish a chunk, wait for an acknowledgement from the device, send the next chunk and so on. The script would subscribe to ACK topic and run onMessage() on each acknowledgement, until the file transfer is complete.

I think I have a workaround: At the end of my onMessage() fuction I just re-subscribe to the same topic. It is not elegant, nor it is efficient, but it seems to work - it keeps the script running.

**Comment by NicolSpies** [comment]
Hi, @kamilfb, thank you for an excellent tool which I am starting to explore. 
The message payloads I receive is in JSON and I need to reformat it to XML before it is saved in the log1.messages file. I have started by trying to get the example in the ScriptingSubscriptions Wiki to run.

I have saved the example javascript 
`function onMessage()
{   
    receivedMessage.setPayload("<tag>" + receivedMessage.getPayload() + "- modified :)</tag>");
    return true;
}`
in a file message.js  in the MQTTSpy directory and entered the file name in the script column of the subscriptions tab of the topic of my connection. I saved, closed and re-opened the connection.
I am expecting the payload message to be modified in the browser and the log1.messages file.
When a message is received it nothing appears to happen and the json payload is unchanged. I am using version 0.52.
What am I doing wrong, please point me in the right direction. 
Regards

**Comment by kamilfb** [comment]
@ddeletic, you could possibly run a normal script (from Scripted publications), that would subscribe to the topic you want, and then in a loop keep checking if there are any new messages. Possibly something like this: https://github.com/kamilfb/mqtt-spy/blob/development/mqtt-spy/src/test/resources/test_cases/test1/tc.js (although the example is a test case, not an ordinary script).
