### ISSUE TITLE
Clearing subscription history for a multi-message list layout only clears the first message list

### ISSUE THREAD

**Issue by blakepercy** [kamilfb/mqtt-spy#98]
**Spy Version = 0.6.0 (beta) Build 51**

Clearing subscription history for a multi-message list layout only clears the first message list.

**Comment by kamilfb** [comment]
Also need to fix the resizing issue and showing all messages when changing number of messages shown.

**Comment by kamilfb** [comment]
@silentsaviour, could you try latest beta? http://tinyurl.com/mqtt-spy-download/mqtt-spy-0.6.0-beta-b52-jar-with-dependencies.jar

**Comment by blakepercy** [comment]
Tested against 0.6.0-beta52 and verified as resolved.
